package squid

import "strings"

// Helpers for editing squid.conf text. squid evaluates http_access rules top
// to bottom and the first match wins, so *where* a generated rule lands
// matters as much as what it says.

const (
	managedBlockPrefix    = "# --- squidadmin"
	managedBlockEndPrefix = "# --- end squidadmin"
)

// policyAnchor returns the line index where deny rules generated by this panel
// must be inserted: right before the first http_access "allow" rule, so they
// are evaluated before any rule that would otherwise let the request through
// (allow localhost, allow localnet, allow <authenticated users>, ...). If the
// config has no allow rule it falls back to the catch-all "deny all", and
// finally to the end of the file.
//
// Lines inside squidadmin-managed blocks are ignored so a block never anchors
// on another block's own rules.
func policyAnchor(lines []string) int {
	inManaged := false
	denyAll := -1

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		switch {
		case strings.HasPrefix(trimmed, managedBlockEndPrefix):
			inManaged = false
			continue
		case strings.HasPrefix(trimmed, managedBlockPrefix):
			inManaged = true
			continue
		}
		if inManaged {
			continue
		}

		if strings.HasPrefix(trimmed, "http_access allow") {
			return i
		}
		if trimmed == "http_access deny all" && denyAll == -1 {
			denyAll = i
		}
	}

	if denyAll != -1 {
		return denyAll
	}
	return len(lines)
}

const (
	accessBlockStart = "# --- squidadmin: access rules (managed, do not edit by hand) ---"
	accessBlockEnd   = "# --- end squidadmin: access rules ---"
)

// denyStageAnchor is where the panel's fixed deny blocks (time restrictions)
// go. The order of everything the panel generates is fixed:
//
//	stock safety denies -> blacklist -> time restrictions -> user access rules
//	-> stock allow rules -> LAN / proxy-auth allows -> deny all
//
// The user's own rules therefore can never override the system denies, yet
// they are evaluated before the stock allow rules (allow localhost, ...).
// Without this, two blocks that both insert "before the first allow" would end
// up in whatever order they were regenerated last.
func denyStageAnchor(lines []string) int {
	for i, l := range lines {
		if strings.TrimSpace(l) == accessBlockStart {
			return i
		}
	}
	return policyAnchor(lines)
}

// insertAt returns lines with block inserted before index i.
func insertAt(lines []string, i int, block []string) []string {
	out := make([]string, 0, len(lines)+len(block))
	out = append(out, lines[:i]...)
	out = append(out, block...)
	out = append(out, lines[i:]...)
	return out
}

// beforeFinalDenyAll returns the index of the last "http_access deny all"
// line, or len(lines) if there is none. Allow rules (LAN access, proxy
// authentication) belong here: after squid's built-in safety denies but
// before the catch-all.
func beforeFinalDenyAll(lines []string) int {
	for i, line := range lines {
		if strings.TrimSpace(line) == "http_access deny all" {
			return i
		}
	}
	return len(lines)
}
